spring:
  application:
    name: spring-boot-testing
  jpa:
    hibernate:
      ddl-auto: update # Hibernate DDL auto-generation strategy (update, create, create-drop, none)
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true # Show SQL statements in the console
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver



    #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect